load("//rules:otbn.bzl", "otbn_library")

package(default_visibility = ["//visibility:public"])

otbn_library(
    name = "p256_base",
    srcs = ["p256_base.s"],
)

otbn_library(
    name = "p256_isoncurve_proj",
    srcs = ["p256_isoncurve_proj.s"],
)

otbn_library(
    name = "p256_shared_key",
    srcs = ["p256_shared_key.s"],
)
