load("//rules:otbn.bzl", "otbn_library")

package(default_visibility = ["//visibility:public"])

otbn_library(
    name = "basemul",
    srcs = ["basemul.s"],
    copts = ["--bnmulv_version_id=2"],
)

otbn_library(
    name = "cbd",
    srcs = ["cbd.s"],
    copts = ["--bnmulv_version_id=2"],
)

otbn_library(
    name = "intt",
    srcs = ["intt.s"],
    copts = ["--bnmulv_version_id=2"],
)

otbn_library(
    name = "ntt",
    srcs = ["ntt.s"],
    copts = ["--bnmulv_version_id=2"],
)

otbn_library(
    name = "pack_keys",
    srcs = ["pack_keys.s"],
    copts = ["--bnmulv_version_id=2"],
)

otbn_library(
    name = "poly",
    srcs = ["poly.s"],
    copts = ["--bnmulv_version_id=2"],
)

otbn_library(
    name = "poly_gen_matrix",
    srcs = ["poly_gen_matrix.s"],
    copts = ["--bnmulv_version_id=2"],
)

otbn_library(
    name = "pack_ciphertext",
    srcs = ["pack_ciphertext.s"],
    copts = ["--bnmulv_version_id=2"],
)

otbn_library(
    name = "mlkem_encap",
    srcs = ["mlkem_encap.s"],
    copts = ["--bnmulv_version_id=2"],
)

otbn_library(
    name = "mlkem_keypair",
    srcs = ["mlkem_keypair.s"],
    copts = ["--bnmulv_version_id=2"],
)

otbn_library(
    name = "mlkem_decap",
    srcs = ["mlkem_decap.s"],
    copts = ["--bnmulv_version_id=2"],
)

otbn_library(
    name = "kmac_sha3",
    srcs = ["kmac_sha3_template.s"],
    copts = ["--bnmulv_version_id=2"],
)
