"""
modp256_dexp.py — bn.modp256 expected results generator

Usage: python3 modp256_dexp.py > ../otbn/test/modp256_test.dexp
"""

P256 = 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff
MAX = (1 << 256) - 1

# P-256 curve parameters
Gx = 0x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296
Gy = 0x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5
Gx2 = 0xa8da539ffce03337030a5a44bcd3266608a32b364bb3295cace17a9da3175abc
Gy2 = 0x72c7c6bec94cf13ab2a1c47c60cb522e04a0e4330df8714c96a2db313c873171

tests = [
    # Basic functional
    ("result1",  0, 0),                  # 0 * 0 = 0
    ("result2",  1, 1),                  # 1 * 1 = 1
    ("result3",  3, 5),                  # 3 * 5 = 15 (no reduction needed)
    # Boundary: p-1
    ("result4",  P256 - 1, 1),           # (p-1) * 1 = p-1
    ("result5",  P256 - 1, 2),           # (p-1) * 2 = p-2 (needs reduction)
    ("result6",  P256 - 1, P256 - 1),    # (p-1)^2 = 1 (max reduction)
    # Real P-256 curve values
    ("result7",  Gx, Gy),                # Gx * Gy mod p
    ("result8",  Gx2, Gy2),              # random large a * b mod p
    # NEW: modulus boundary
    ("result9",  P256, 1),               # p * 1 = 0
    ("result10", P256 + 1, 1),           # (p+1) * 1 = 1
    # NEW: max value stress
    ("result11", MAX, MAX),              # (2^256-1)^2 mod p (max product)
    ("result12", MAX, 1),                # (2^256-1) * 1 mod p
    ("result13", MAX, P256 - 1),         # max * (p-1) mod p (mixed stress)
]

print("# modp256_test.dexp — bn.modp256 expected results")
print("# Generated by modp256_dexp.py")
for name, a, b in tests:
    r = (a * b) % P256
    print(f"{name}: {r:064x}")
