#!/usr/bin/env python3
"""P-256 Solinas reduction - math verification + ISS test data generator.

Verifies the standard NIST Solinas formula against (a*b) % P256.
Generates modp256_test.dexp for the ISS unit test.

Usage:
  python3 modp256_dexp.py                # math verification only
  python3 modp256_dexp.py --dexp <out>   # generate .dexp for ISS test
"""
import random
import sys

P256 = 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff


def solinas_reduce_256(S: int, R: int) -> int:
    """Solinas reduction: compute (S*2^256 + R) mod P256."""
    s = [(S >> (224 - i * 32)) & 0xFFFFFFFF for i in range(8)]
    s1 = (s[0]<<224) | (s[1]<<192) | (s[2]<<160) | (s[3]<<128) | (s[4]<<96)
    s2 = (s[0]<<192) | (s[1]<<160) | (s[2]<<128) | (s[3]<<96)
    s3 = (s[0]<<224) | (s[1]<<192) | (s[5]<<64) | (s[6]<<32) | s[7]
    s4 = (s[7]<<224) | (s[2]<<192) | (s[0]<<160) | (s[1]<<128) | \
         (s[2]<<96)  | (s[4]<<64)  | (s[5]<<32)  | s[6]
    d1 = (s[5]<<224) | (s[7]<<192) | (s[2]<<64) | (s[3]<<32) | s[4]
    d2 = (s[4]<<224) | (s[6]<<192) | (s[0]<<96) | (s[1]<<64) | (s[2]<<32) | s[3]
    d3 = (s[3]<<224) | (s[5]<<160) | (s[6]<<128) | (s[7]<<96) | \
         (s[0]<<64)  | (s[1]<<32)  | s[2]
    d4 = (s[2]<<224) | (s[4]<<160) | (s[5]<<128) | (s[6]<<96) | (s[0]<<32) | s[1]
    return (R + 2*s1 + 2*s2 + s3 + s4 - d1 - d2 - d3 - d4) % P256


def modp256(a: int, b: int) -> int:
    assert 0 <= a < P256 and 0 <= b < P256
    prod = a * b
    return solinas_reduce_256(prod >> 256, prod & ((1<<256)-1))


def run_tests():
    print(f"P256 = {P256:#x}")
    print("Running 2000 random tests ...", end=" ", flush=True)
    for i in range(2000):
        a = random.randint(0, P256-1)
        b = random.randint(0, P256-1)
        assert modp256(a, b) == (a*b) % P256, f"FAIL test {i}"
    print("OK")
    for a, b in [(0,0), (1,1), (P256-1,P256-1), ((1<<256)-1,(1<<256)-1), (1,P256-1)]:
        a, b = a%P256, b%P256
        assert modp256(a, b) == (a*b)%P256
    print("  5 edge cases OK")
    print("All tests passed: Solinas formula === (a*b) %% P256")


def generate_dexp(path: str):
    """Generate modp256_test.dexp — must match modp256_test.s labels exactly."""
    P = P256
    pm1 = P - 1
    Gx = 0x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296
    Gy = 0x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5

    labels = [
        ('t1_3x5',     (3*5) % P),
        ('t2_sq',      (2*2) % P),
        ('t3_zero',    0),
        ('t4_id',      (3*1) % P),
        ('t5_selfref', (3*5) % P),
        ('t6_wrd2',    (1*7) % P),
        ('t7_bb1',     (4*9) % P),
        ('t7_bb2',     (((4*9)%P)*4) % P),
        ('t8_pm1sq',   (pm1*pm1) % P),
        ('t9_lid',     (Gx*1) % P),
        ('t10_GxGy',   (Gx*Gy) % P),
    ]
    with open(path, 'w') as f:
        f.write('# modp256_test.dexp — matches modp256_test.s labels\n')
        f.write('# Generated by modp256_dexp.py --dexp\n\n')
        for name, val in labels:
            f.write(f'{name}: {val:064x}\n')
    print(f"Generated {path} ({len(labels)} labels)")


if __name__ == '__main__':
    run_tests()
    if len(sys.argv) > 1 and sys.argv[1] == '--dexp':
        out = sys.argv[2] if len(sys.argv) > 2 else 'modp256_test.dexp'
        generate_dexp(out)
