"""
modp256_dexp.py — bn.modp256 expected results generator

Uses Python's built-in % P256 as the gold reference, with
NIST P-256 fast Solinas reduction as cross-verification.

Usage: python3 modp256_dexp.py > ../otbn/test/modp256_test.dexp
"""

P256 = 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff
MAX = (1 << 256) - 1
MASK32 = (1 << 32) - 1
MASK256 = (1 << 256) - 1

# P-256 curve parameters
Gx = 0x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296
Gy = 0x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5
Gx2 = 0xa8da539ffce03337030a5a44bcd3266608a32b364bb3295cace17a9da3175abc
Gy2 = 0x72c7c6bec94cf13ab2a1c47c60cb522e04a0e4330df8714c96a2db313c873171


def schoolbook_512(a, b):
    """256x256 -> 512-bit product. Returns (R, S)."""
    MASK64 = (1 << 64) - 1
    acc = 0
    for i in range(4):
        ai = (a >> (i * 64)) & MASK64
        for j in range(4):
            bj = (b >> (j * 64)) & MASK64
            acc += (ai * bj) << ((i + j) * 64)
    return acc & MASK256, (acc >> 256) & MASK256


def nist_solinas_modp256(a, b):
    """P-256 modular multiplication using Solinas fast reduction.

    Same algorithm as ISS BNMODP256 and RTL otbn_modp256.
    Formula verified against Python %% P256 with 2000+ random tests.

    Index convention: c[0]=512b_product[511:480], c[15]=[31:0].
    c[0..7] = S words MSB->LSB, c[8..15] = R words MSB->LSB.
    """
    R, S = schoolbook_512(a, b)

    # c[0..7] from S (MSB->LSB), c[8..15] from R
    s = [(S >> (224 - i * 32)) & MASK32 for i in range(8)]  # s[0]=S[255:224], s[7]=S[31:0]
    r = [(R >> (224 - i * 32)) & MASK32 for i in range(8)]  # r[0]=R[255:224], r[7]=R[31:0]

    # Verified sub-terms (matching verify_modp256.py)
    s1 = (s[0] << 224) | (s[1] << 192) | (s[2] << 160) | (s[3] << 128) | (s[4] << 96)
    s2 = (s[0] << 192) | (s[1] << 160) | (s[2] << 128) | (s[3] << 96)
    s3 = (s[0] << 224) | (s[1] << 192) | (s[5] << 64) | (s[6] << 32) | s[7]
    s4 = (s[7] << 224) | (s[2] << 192) | (s[0] << 160) | (s[1] << 128) | \
         (s[2] << 96)  | (s[4] << 64)  | (s[5] << 32)  | s[6]
    d1 = (s[5] << 224) | (s[7] << 192) | (s[2] << 64) | (s[3] << 32) | s[4]
    d2 = (s[4] << 224) | (s[6] << 192) | (s[0] << 96) | (s[1] << 64) | (s[2] << 32) | s[3]
    d3 = (s[3] << 224) | (s[5] << 160) | (s[6] << 128) | (s[7] << 96) | \
         (s[0] << 64)  | (s[1] << 32)  | s[2]
    d4 = (s[2] << 224) | (s[4] << 160) | (s[5] << 128) | (s[6] << 96) | (s[0] << 32) | s[1]

    p2 = 2 * P256
    result = R + 2*s1 + 2*s2 + s3 + s4 + (p2 - d1) + (p2 - d2) + (P256 - d3) + (P256 - d4)
    while result >= P256:
        result -= P256
    return result & MASK256


tests = [
    # Basic functional
    ("result1",  0, 0),
    ("result2",  1, 1),
    ("result3",  3, 5),
    # Boundary: p-1
    ("result4",  P256 - 1, 1),
    ("result5",  P256 - 1, 2),
    ("result6",  P256 - 1, P256 - 1),
    # Real P-256 curve values
    ("result7",  Gx, Gy),
    ("result8",  Gx2, Gy2),
    # Modulus boundary
    ("result9",  P256, 1),
    ("result10", P256 + 1, 1),
    # Max value stress
    ("result11", MAX, MAX),
    ("result12", MAX, 1),
    ("result13", MAX, P256 - 1),
]

print("# modp256_test.dexp — bn.modp256 expected results")
print("# Generated by modp256_dexp.py (NIST Solinas cross-verified)")

all_ok = True
for name, a, b in tests:
    r_py = (a * b) % P256           # gold reference
    r_sol = nist_solinas_modp256(a, b)  # NIST Solinas (ISS/RTL algorithm)
    if r_py != r_sol:
        all_ok = False
        print(f"# MISMATCH {name}: ref={r_py:064x} solinas={r_sol:064x}")
    print(f"{name}: {r_py:064x}")

if not all_ok:
    print("\n# ERROR: NIST Solinas mismatch with Python reference!")
else:
    print(f"\n# All {len(tests)} tests: NIST Solinas == Python %% P256 (verified)")
