"""
dexp.py — SHA3/SHAKE 硬件期望值生成器

关键：硬件 RUN 命令 FORCE keccak-f, 不等 block 自然耗尽。
PyCryptodome 的 read(N) 只在 N 耗尽 buffer 时触发 keccak-f。
必须显式 read 掉 block 剩余字节来模拟 RUN 行为。

用法: python3 dexp.py > sha3_test.dexp
"""

import hashlib
import sys

# PyCryptodome: read() 支持流式读写
from Crypto.Hash import SHAKE128, SHAKE256

# ── 固定消息 ──────────────────────────────────────────

MSG_8B   = b"what do "
MSG_32B  = b"\x00" * 32
MSG_33B  = b"\x00" * 32 + b"\x01"
MSG_35B  = b"\x00" * 32 + b"\x01\x02\x03"
MSG_64B  = b"\x00" * 64
MSG_127B = b"\x00" * 127                  # 3 WDR + 31B tail
MSG_256B = b"what do " * 32               # 256 bytes (8 WDRs = 32 words)
MSG_136B = b"rate136!" * 17               # 136 bytes = exact SHA3-256 rate (1088b)
MSG_137B = b"rate136!" * 17 + b"\xff"

# ── 工具函数 ──────────────────────────────────────────

def hw(data: bytes) -> bytes:
    """硬件 DMEM 字节序: 32B 块整体反转"""
    return data[::-1]

def hx(data: bytes) -> str:
    return data.hex()

def sha3_256(msg): return hashlib.sha3_256(msg).digest()
def sha3_512(msg): return hashlib.sha3_512(msg).digest()

# ── 输出 ──────────────────────────────────────────────

print("# sha3_test.dexp — matches sha3_test.s ELF labels")
print("# Generated by dexp.py (RUN-aware, uses PyCryptodome read())")
print()

# SHA3
print(f"sha3_256_empty_out: {hx(hw(sha3_256(b'')))}")
print(f"sha3_512_empty_out: {hx(hw(sha3_512(b'')))}")
print(f"sha3_256_msg_out: {hx(hw(sha3_256(MSG_8B)))}")
print(f"sha3_512_msg_out: {hx(hw(sha3_512(MSG_8B)))}")
print(f"sha3_256_32b_out: {hx(hw(sha3_256(MSG_32B)))}")
print(f"sha3_256_33b_out: {hx(hw(sha3_256(MSG_33B)))}")
print(f"sha3_256_35b_out: {hx(hw(sha3_256(MSG_35B)))}")
print(f"sha3_256_64b_out: {hx(hw(sha3_256(MSG_64B)))}")
print(f"sha3_256_127b_out: {hx(hw(sha3_256(MSG_127B)))}")
print(f"sha3_256_136b_out: {hx(hw(sha3_256(MSG_136B)))}")
print(f"sha3_256_136b_plus1_out: {hx(hw(sha3_256(MSG_137B)))}")
print()

# ── SHAKE empty-message (FIPS 202: pad10*1 required for empty messages) ──
# SHAKE128("") — 1111 || pad10*1 → 0x1F || 0x00×165 || 0x80
print(f"shake128_empty_out: {hx(hw(SHAKE128.new(data=b'').read(32)))}")
# SHAKE256("") — 1111 || pad10*1 → 0x1F || 0x00×133 || 0x80
print(f"shake256_empty_out: {hx(hw(SHAKE256.new(data=b'').read(32)))}")
print()

# SHAKE without RUN (连续 squeeze, 不超 rate)
# SHAKE128 rate=168B, SHAKE256 rate=136B → 32B 远小于 rate, 正常读
print(f"shake128_out: {hx(hw(SHAKE128.new(data=MSG_8B).read(32)))}")
print(f"shake256_out: {hx(hw(SHAKE256.new(data=MSG_8B).read(32)))}")
print()

# SHAKE128 64B without RUN (64B < 168B rate, 直接读)
s128 = SHAKE128.new(data=MSG_8B).read(64)
print(f"shake128_64b_out_1: {hx(hw(s128[0:32]))}")
print(f"shake128_64b_out_2: {hx(hw(s128[32:64]))}")
print()

# ── SHAKE: 连续 squeeze（auto-RUN 在 block 耗尽时触发）──

# SHAKE128 1run: 连续 64B
s128 = SHAKE128.new(data=MSG_8B).read(64)
print(f"shake128_1run_b1: {hx(hw(s128[0:32]))}")
print(f"shake128_1run_b2: {hx(hw(s128[32:64]))}")
print()

# SHAKE256 1run: 连续 64B
s256 = SHAKE256.new(data=MSG_8B).read(64)
print(f"shake256_1run_b1: {hx(hw(s256[0:32]))}")
print(f"shake256_1run_b2: {hx(hw(s256[32:64]))}")
print()

# SHAKE128 rate-cross: 6×32B 连续读取 = 192B > 168B rate
# auto-RUN 在 6th squeeze 的第2个word自动触发(168B耗尽)
s = SHAKE128.new(data=MSG_256B).read(192)
batches = [s[i:i+32] for i in range(0, 192, 32)]
for i, b in enumerate(batches):
    print(f"rcx_b{i+1}: {hx(hw(b))}")

# ── cSHAKE (≡ SHAKE with empty customization strings) ──
# bytepad(encode_string("")||encode_string("")) = "", so cSHAKE = SHAKE
print(f"cshake128_empty_out: {hx(hw(SHAKE128.new(data=b'').read(32)))}")
print(f"cshake256_empty_out: {hx(hw(SHAKE256.new(data=b'').read(32)))}")
print(f"cshake128_out: {hx(hw(SHAKE128.new(data=MSG_8B).read(32)))}")
print(f"cshake256_out: {hx(hw(SHAKE256.new(data=MSG_8B).read(32)))}")
