load("//rules:otbn.bzl", "otbn_binary")

package(default_visibility = ["//visibility:public"])

otbn_binary(
    name = "bnmulv8S_smoke_test",
    srcs = [
        "bnmulv8S_smoke_test.s",
    ],
    copts = ["--bnmulv_version_id=2"],
)

otbn_binary(
    name = "bnmulv16H_smoke_test",
    srcs = [
        "bnmulv16H_smoke_test.s",
    ],
    copts = ["--bnmulv_version_id=2"],
)

otbn_binary(
    name = "bnmulvl8S_smoke_test",
    srcs = [
        "bnmulvl8S_smoke_test.s",
    ],
    copts = ["--bnmulv_version_id=2"],
)

otbn_binary(
    name = "bnmulvl16H_smoke_test",
    srcs = [
        "bnmulvl16H_smoke_test.s",
    ],
    copts = ["--bnmulv_version_id=2"],
)

otbn_binary(
    name = "bnaddsubv_smoke_test",
    srcs = [
        "bnaddsubv_smoke_test.s",
    ],
    copts = ["--bnmulv_version_id=2"],
)

otbn_binary(
    name = "bnaddsubvm_smoke_test",
    srcs = [
        "bnaddsubvm_smoke_test.s",
    ],
    copts = ["--bnmulv_version_id=2"],
)

otbn_binary(
    name = "bnshv_smoke_test",
    srcs = [
        "bnshv_smoke_test.s",
    ],
    copts = ["--bnmulv_version_id=2"],
)

otbn_binary(
    name = "bntrn_smoke_test",
    srcs = [
        "bntrn_smoke_test.s",
    ],
    copts = ["--bnmulv_version_id=2"],
)

