load("//rules:otbn.bzl", "otbn_library")

package(default_visibility = ["//visibility:public"])

otbn_library(
    name = "hkdf_sha3_256",
    srcs = ["hkdf_sha3_256.s"],
)

otbn_library(
    name = "hmac_sha3",
    srcs = ["hmac_sha3.s"],
)

otbn_library(
    name = "kmac_sha3_template",
    srcs = ["kmac_sha3_template.s"],
)
