"""
dexp.py — SHA3/SHAKE 硬件期望值生成器

关键：硬件 RUN 命令 FORCE keccak-f, 不等 block 自然耗尽。
PyCryptodome 的 read(N) 只在 N 耗尽 buffer 时触发 keccak-f。
必须显式 read 掉 block 剩余字节来模拟 RUN 行为。

用法: python3 dexp.py > sha3_test.dexp
"""

import hashlib
import sys

# PyCryptodome: read() 支持流式读写
from Crypto.Hash import SHAKE128, SHAKE256

# ── 固定消息 ──────────────────────────────────────────

MSG_8B   = b"what do "
MSG_32B  = b"\x00" * 32
MSG_33B  = b"\x00" * 32 + b"\x01"
MSG_35B  = b"\x00" * 32 + b"\x01\x02\x03"
MSG_64B  = b"\x00" * 64
MSG_127B = b"\x00" * 127                  # 3 WDR + 31B tail
MSG_256B = b"what do " * 32               # 256 bytes (8 WDRs = 32 words)

# ── 工具函数 ──────────────────────────────────────────

def hw(data: bytes) -> bytes:
    """硬件 DMEM 字节序: 32B 块整体反转"""
    return data[::-1]

def hx(data: bytes) -> str:
    return data.hex()

def sha3_256(msg): return hashlib.sha3_256(msg).digest()
def sha3_512(msg): return hashlib.sha3_512(msg).digest()

# ── 输出 ──────────────────────────────────────────────

print("# sha3_test.dexp — matches sha3_test.s ELF labels")
print("# Generated by dexp.py (RUN-aware, uses PyCryptodome read())")
print()

# SHA3
print(f"sha3_256_empty_out: {hx(hw(sha3_256(b'')))}")
print(f"sha3_512_empty_out: {hx(hw(sha3_512(b'')))}")
print(f"sha3_256_msg_out: {hx(hw(sha3_256(MSG_8B)))}")
print(f"sha3_512_msg_out: {hx(hw(sha3_512(MSG_8B)))}")
print(f"sha3_256_32b_out: {hx(hw(sha3_256(MSG_32B)))}")
print(f"sha3_256_33b_out: {hx(hw(sha3_256(MSG_33B)))}")
print(f"sha3_256_35b_out: {hx(hw(sha3_256(MSG_35B)))}")
print(f"sha3_256_64b_out: {hx(hw(sha3_256(MSG_64B)))}")
print(f"sha3_256_127b_out: {hx(hw(sha3_256(MSG_127B)))}")
print()

# SHAKE without RUN (连续 squeeze, 不超 rate)
# SHAKE128 rate=168B, SHAKE256 rate=136B → 32B 远小于 rate, 正常读
print(f"shake128_out: {hx(hw(SHAKE128.new(data=MSG_8B).read(32)))}")
print(f"shake256_out: {hx(hw(SHAKE256.new(data=MSG_8B).read(32)))}")
print()

# SHAKE128 64B without RUN (64B < 168B rate, 直接读)
s128 = SHAKE128.new(data=MSG_8B).read(64)
print(f"shake128_64b_out_1: {hx(hw(s128[0:32]))}")
print(f"shake128_64b_out_2: {hx(hw(s128[32:64]))}")
print()

# ── SHAKE + RUN: 读 N 字节后 FORCE keccak-f, 再读 M 字节 ─

def shake128_run(msg, n1, n2, rate=168):
    """SHAKE128: read n1 bytes, RUN (discard block remaining), read n2 bytes"""
    s = SHAKE128.new(data=msg)
    b1 = s.read(n1)
    remaining = rate - n1
    if remaining > 0:
        s.read(remaining)  # force keccak-f
    b2 = s.read(n2)
    return b1, b2

def shake256_run(msg, n1, n2, rate=136):
    """SHAKE256: read n1 bytes, RUN, read n2 bytes"""
    s = SHAKE256.new(data=msg)
    b1 = s.read(n1)
    remaining = rate - n1
    if remaining > 0:
        s.read(remaining)
    b2 = s.read(n2)
    return b1, b2

# SHAKE128 1run
b1, b2 = shake128_run(MSG_8B, 32, 32)
print(f"shake128_1run_b1: {hx(hw(b1))}")
print(f"shake128_1run_b2: {hx(hw(b2))}")
print()

# SHAKE256 1run
b1, b2 = shake256_run(MSG_8B, 32, 32)
print(f"shake256_1run_b1: {hx(hw(b1))}")
print(f"shake256_1run_b2: {hx(hw(b2))}")
print()

# SHAKE128 rate-cross: 5 squeezes (160B) + RUN + 1 squeeze (32B)
s = SHAKE128.new(data=MSG_256B)
batches = []
for i in range(5):
    batches.append(s.read(32))
# After 5*32=160B, remaining in block 1 = 168-160 = 8B
# RUN: discard 8B → force keccak-f
s.read(8)
batches.append(s.read(32))
for i, b in enumerate(batches):
    print(f"rcx_b{i+1}: {hx(hw(b))}")
