#!/usr/bin/env python3
"""Generate NIST KAT expected values for otbn_kmac testbench.

Computes SHA3-256, SHA3-512, SHAKE128 digest values using Python hashlib,
and generates a SystemVerilog include file with packed 64-bit little-endian words.
"""

import hashlib
import sys
from pathlib import Path

TEST_VECTORS = [
    # (name, algo, msg_bytes, digest_bits_or_squeeze_bytes)
    # SHA3
    ("SHA3-256 empty",         "sha3_256",  b"",             256),
    ("SHA3-256 abc",           "sha3_256",  b"abc",          256),
    ("SHA3-256 128B pad=1",    "sha3_256",  b"\x00"*128,    256),
    ("SHA3-256 136B rate-full","sha3_256",  b"\x00"*136,    256),
    ("SHA3-512 empty",         "sha3_512",  b"",             512),
    ("SHA3-512 64B pad=1",     "sha3_512",  b"\x00"*64,     512),
    # SHAKE128
    ("SHAKE128 empty",         "shake128",  b"",             256),
    ("SHAKE128 33B",           "shake128",  b"\x00"*33,     256),
    ("SHAKE128 34B_to_32B",    "shake128",  b"\x00"*34,     256),
    ("SHAKE128 35B",           "shake128",  b"\x00"*35,     256),
    ("SHAKE128 127B",          "shake128",  b"\x00"*127,    256),
    ("SHAKE128 168B_to_64B",   "shake128",  b"\x00"*168,    512),
    ("SHAKE128 168B_256B rate-cross","shake128",b"\x00"*168,2048),  # 32 words > 21 rate
    # SHAKE256
    ("SHAKE256 empty",         "shake256",  b"",             256),
    ("SHAKE256 what do ",      "shake256",  b"what do ",     256),
]


def digest_to_64bit_words_le(digest_bytes: bytes) -> list[int]:
    """Convert byte digest to 64-bit little-endian words."""
    words = []
    for i in range(0, len(digest_bytes), 8):
        chunk = digest_bytes[i:i+8]
        if len(chunk) < 8:
            chunk = chunk + b"\x00" * (8 - len(chunk))
        word = int.from_bytes(chunk, byteorder="little")
        words.append(word)
    return words


def main():
    out_path = Path(__file__).parent / "kat_expected.svh"

    lines = [
        "// Auto-generated by gen_kat.py — DO NOT EDIT",
        "// NIST KAT expected values for otbn_kmac testbench",
        "// Generated: " + str(Path(__file__).stat().st_mtime),
        "",
    ]

    for name, algo, msg, out_bits in TEST_VECTORS:
        h = hashlib.new(algo)
        h.update(msg)

        if "shake" in algo:
            digest = h.digest(out_bits // 8)
        else:
            digest = h.digest()

        words = digest_to_64bit_words_le(digest)

        # Sanity: print hex digest
        hex_digest = digest.hex()
        print(f"{name}: {hex_digest}")

        # Generate SV array
        num_words = len(words)
        macro_name = name.replace(" ", "_").replace("-", "_").replace("(", "").replace(")", "")
        macro_name = macro_name.replace("=", "_eq_").replace(">", "_to_")
        macro_name = macro_name.upper()

        lines.append(f"// {name}: {hex_digest}")
        lines.append(f"localparam logic [63:0] kat_{macro_name} [{num_words}] = '{{")
        for j, w in enumerate(words):
            comma = "," if j < num_words - 1 else ""
            lines.append(f"  64'h{w:016x}{comma}")
        lines.append("};")
        lines.append("")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote {out_path}")


if __name__ == "__main__":
    main()
