#!/usr/bin/env python3
"""Generate KAT expected values matching kmac_smoke_test + run_test + pad_edge_test."""
import hashlib
from pathlib import Path

MSG_8B   = b"what do "
MSG_136B = b"rate136!" * 17
MSG_256B = b"what do " * 32
MSG_4096B= b"what do " * 512

def words_le(d, n):
    return [int.from_bytes(d[i*8:i*8+8], 'little') for i in range(n)]

def sha3_256(m): return hashlib.new("sha3_256", m).digest()
def sha3_512(m): return hashlib.new("sha3_512", m).digest()
def shake128(m,n): return hashlib.new("shake128", m).digest(n)
def shake256(m,n): return hashlib.new("shake256", m).digest(n)

# (macro_suffix, digest_bytes, num_words)
TESTS = [
    # === SHA3 smoke tests ===
    ("SHA3_256_EMPTY",        sha3_256(b""), 4),
    ("SHA3_512_EMPTY",        sha3_512(b""), 8),
    ("SHA3_256_MSG",          sha3_256(MSG_8B), 4),
    ("SHA3_512_MSG",          sha3_512(MSG_8B), 8),
    ("SHA3_256_32B",          sha3_256(b"\x00"*32), 4),
    ("SHA3_256_33B",          sha3_256(b"\x00"*32+b"\x01"), 4),
    ("SHA3_256_35B",          sha3_256(b"\x00"*32+b"\x01\x02\x03"), 4),
    ("SHA3_256_64B",          sha3_256(b"\x00"*64), 4),
    ("SHA3_256_2048B",        sha3_256(MSG_256B), 4),
    ("SHA3_256_127B",         sha3_256(b"\x00"*127), 4),
    ("SHA3_256_136B",         sha3_256(MSG_136B), 4),
    ("SHA3_256_136B_PLUS1",   sha3_256(MSG_136B+b"\xff"), 4),
    # === SHAKE smoke tests ===
    ("SHAKE128_EMPTY",        shake128(b"", 32), 4),
    ("SHAKE256_EMPTY",        shake256(b"", 32), 4),
    ("SHAKE128_MSG",          shake128(MSG_8B, 32), 4),
    ("SHAKE256_MSG",          shake256(MSG_8B, 32), 4),
    ("SHAKE128_64B_RUN_B1",   shake128(MSG_8B, 64)[0:32], 4),
    ("SHAKE128_64B_RUN_B2",   shake128(MSG_8B, 64)[32:64], 4),
    ("SHAKE128_4096B",        shake128(MSG_4096B, 32), 4),
    ("SHAKE256_4096B",        shake256(MSG_4096B, 32), 4),
    ("SHAKE128_34B_TO_32B",   shake128(b"\x00"*34, 32), 4),
    ("SHAKE128_33B",          shake128(b"\x00"*33, 32), 4),
    ("SHAKE128_35B",          shake128(b"\x00"*35, 32), 4),
    ("SHAKE128_127B",         shake128(b"\x00"*127, 32), 4),
    ("SHAKE128_168B_TO_64B",  shake128(b"\x00"*168, 64), 8),
    # === Pad edge tests ===
    ("SHA3_256_128B_PAD1",    sha3_256(b"\x00"*128), 4),
    ("SHA3_512_64B_PAD1",     sha3_512(b"\x00"*64), 8),
    ("SHAKE128_160B_PAD1",    shake128(b"\x00"*160, 32), 4),
    ("SHAKE256_128B_PAD1",    shake256(b"\x00"*128, 32), 4),
    ("SHA3_256_120B_PAD2",    sha3_256(b"\x00"*120), 4),
    ("SHA3_512_56B_PAD2",     sha3_512(b"\x00"*56), 8),
    # === SHAKE rate-cross (256B msg → 6×32B squeeze) ===
    ("SHAKE128_RC",            shake128(MSG_256B, 192), 24),
]

out = Path(__file__).parent / "kat_expected.svh"
lines = [
    "// Auto-generated by gen_kat.py — matches kmac_smoke_test + run_test + pad_edge_test",
    f"// Generated: {Path(__file__).stat().st_mtime}",
    "",
]
for name, digest, nw in TESTS:
    w = words_le(digest, nw)
    print(f"{name}: {digest.hex()}")
    lines.append(f"// {name}")
    lines.append(f"localparam logic [63:0] kat_{name} [{nw}] = '{{")
    for j, x in enumerate(w):
        lines.append(f"  64'h{x:016x}," if j < nw-1 else f"  64'h{x:016x}")
    lines.append("};")
    lines.append("")
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"\nWrote {out}")
