// Auto-generated by gen_kat.py — matches kmac_smoke_test + run_test + pad_edge_test
// Generated: 1780931809.1339734

// SHA3_256_EMPTY
localparam logic [63:0] kat_SHA3_256_EMPTY [4] = '{
  64'h66d71ebff8c6ffa7,
  64'h62d661a05647c151,
  64'hfa493be44dff80f5,
  64'h4a43f8804b0ad882
};

// SHA3_512_EMPTY
localparam logic [63:0] kat_SHA3_512_EMPTY [8] = '{
  64'hc59a3aa2cc739fa6,
  64'h6e755a18dc67b5c8,
  64'h5958e24f1682c997,
  64'ha6805c47c1dcd1e0,
  64'h4cf9f5f13a12b215,
  64'h58c53a2c40e9e311,
  64'he3d3b6959d1900f5,
  64'h26cd1d2886857501
};

// SHA3_256_MSG
localparam logic [63:0] kat_SHA3_256_MSG [4] = '{
  64'h7aaaab2bc8893573,
  64'hae4272b7a3a3f596,
  64'h4ccc157fe87f1aab,
  64'h0adb3beee4dd31ac
};

// SHA3_512_MSG
localparam logic [63:0] kat_SHA3_512_MSG [8] = '{
  64'h9c833da9ef4bf26d,
  64'h585096981dbf174f,
  64'hea351d6e4cf1f119,
  64'hca8edb29ddf5afe0,
  64'h32109a961c6aed55,
  64'h36d228e0af285412,
  64'h8863b15edeff0295,
  64'hc1a7716cf988acab
};

// SHA3_256_32B
localparam logic [63:0] kat_SHA3_256_32B [4] = '{
  64'hd94db40c9791629e,
  64'h6fd8f9ca9bc70840,
  64'h47a0b2a59bb4b418,
  64'h4e9e3bed9971db81
};

// SHA3_256_33B
localparam logic [63:0] kat_SHA3_256_33B [4] = '{
  64'h1710e5e4446520aa,
  64'h20b4e8a428c213b3,
  64'hab878e8a1fa6bb35,
  64'h7cfa19c95d13e1d5
};

// SHA3_256_35B
localparam logic [63:0] kat_SHA3_256_35B [4] = '{
  64'ha6142459e5e2b318,
  64'h30a312f8b8969af3,
  64'h1ceeda8432f52f1a,
  64'hffc655359a01ec4a
};

// SHA3_256_64B
localparam logic [63:0] kat_SHA3_256_64B [4] = '{
  64'h7e55cc6faba10f07,
  64'h6967191f94424dd1,
  64'h8d2a04b91e554830,
  64'he0815ed7fb7a050a
};

// SHA3_256_2048B
localparam logic [63:0] kat_SHA3_256_2048B [4] = '{
  64'haded94bdf20c07ff,
  64'hfa9d741509850a93,
  64'hd3e8b2397c061f7a,
  64'h42c0c26444eae160
};

// SHA3_256_127B
localparam logic [63:0] kat_SHA3_256_127B [4] = '{
  64'hb676c3f60335377c,
  64'hcaa6cd6ff28f6752,
  64'h30976da97c1804ad,
  64'h93c8296230ae5316
};

// SHA3_256_136B
localparam logic [63:0] kat_SHA3_256_136B [4] = '{
  64'hf021d7780d1f1207,
  64'h54113eb36c60750b,
  64'h45bcaf86e6c93e81,
  64'h629f1c5a50e6eca7
};

// SHA3_256_136B_PLUS1
localparam logic [63:0] kat_SHA3_256_136B_PLUS1 [4] = '{
  64'h09587c04d9bc984a,
  64'h1718f7cae1e898a0,
  64'h022fe347f8202a4a,
  64'h6333585d83042c0d
};

// SHAKE128_EMPTY
localparam logic [63:0] kat_SHAKE128_EMPTY [4] = '{
  64'h7d828fe8a42b9c7f,
  64'h3e85057650456061,
  64'h88bceff693803bd7,
  64'h26ef66faac6e1aeb
};

// SHAKE256_EMPTY
localparam logic [63:0] kat_SHAKE256_EMPTY [4] = '{
  64'h138da80b2bddb946,
  64'h24eb3e74eb3f3b23,
  64'h821bb862ea52cd3f,
  64'h2f76d56e64270cb5
};

// SHAKE128_MSG
localparam logic [63:0] kat_SHAKE128_MSG [4] = '{
  64'hfdae9bcd8e16d337,
  64'he784953db2364d8e,
  64'hcca2cba1394819d6,
  64'h47c6239f137ef957
};

// SHAKE256_MSG
localparam logic [63:0] kat_SHAKE256_MSG [4] = '{
  64'h9730bb4809ab1ce2,
  64'hcf6db5ab068b4764,
  64'h84dd3e576909807a,
  64'h927bf3216e42f3bf
};

// SHAKE128_64B_RUN_B1
localparam logic [63:0] kat_SHAKE128_64B_RUN_B1 [4] = '{
  64'hfdae9bcd8e16d337,
  64'he784953db2364d8e,
  64'hcca2cba1394819d6,
  64'h47c6239f137ef957
};

// SHAKE128_64B_RUN_B2
localparam logic [63:0] kat_SHAKE128_64B_RUN_B2 [4] = '{
  64'hbcf71edc12b53709,
  64'h0c160528f8357457,
  64'h95f66cabb16d0c39,
  64'he2b38a681d2781fb
};

// SHAKE128_4096B
localparam logic [63:0] kat_SHAKE128_4096B [4] = '{
  64'h9473571dc428ee73,
  64'hecdee1609d32b2ec,
  64'h8cd9fec5e94e90c2,
  64'hf5500c644a40afc7
};

// SHAKE256_4096B
localparam logic [63:0] kat_SHAKE256_4096B [4] = '{
  64'h7c319ad8e1eaa8ec,
  64'hd9eb779090c3350b,
  64'h83453bd42d02ffa0,
  64'habafb3031b7918ff
};

// SHAKE128_34B_TO_32B
localparam logic [63:0] kat_SHAKE128_34B_TO_32B [4] = '{
  64'h0154bc9b80d9df49,
  64'hedf5199a6accab4a,
  64'h72910219d957ad48,
  64'h5ec7c62a7889b601
};

// SHAKE128_33B
localparam logic [63:0] kat_SHAKE128_33B [4] = '{
  64'hf552888abace4fdf,
  64'ha5a4ffae6d9b2da1,
  64'h0fb372145f5522dd,
  64'hf39ce28566a76bfa
};

// SHAKE128_35B
localparam logic [63:0] kat_SHAKE128_35B [4] = '{
  64'hdc8b599d122800bb,
  64'h9e64a83d7394ee57,
  64'hb830695629722d1b,
  64'h35611c114aa0e533
};

// SHAKE128_127B
localparam logic [63:0] kat_SHAKE128_127B [4] = '{
  64'he06be5acd33f58c6,
  64'h9b243e83c25d5399,
  64'hf317af08a4c30771,
  64'hc861041feb00c284
};

// SHAKE128_168B_TO_64B
localparam logic [63:0] kat_SHAKE128_168B_TO_64B [8] = '{
  64'hb20c874847ff007c,
  64'h4774ff8a07dca46d,
  64'hb6c79111fa53b17a,
  64'hab1fcc1ec0a6fe36,
  64'h9a27e077485469ff,
  64'hdd04d939d81da0cf,
  64'h93680501c509aa0c,
  64'h075e526f9a4fffe5
};

// SHA3_256_128B_PAD1
localparam logic [63:0] kat_SHA3_256_128B_PAD1 [4] = '{
  64'h94cfffdbc9890604,
  64'h8c6d68c5eecd0a62,
  64'h701a3c8f5fc8d135,
  64'h48a13ed38ed588b9
};

// SHA3_512_64B_PAD1
localparam logic [63:0] kat_SHA3_512_64B_PAD1 [8] = '{
  64'h4c8a32a1f5923d24,
  64'hf7e60ea66dcbf4c9,
  64'h11fcd47a2f4762b3,
  64'h4c576150c846367e,
  64'h908dd9fcbd10e112,
  64'ha7445bff6b9bd1f0,
  64'h22853a5c97a19dc6,
  64'h283c557e21b95e09
};

// SHAKE128_160B_PAD1
localparam logic [63:0] kat_SHAKE128_160B_PAD1 [4] = '{
  64'h7bdd81a6e39264a4,
  64'h9e12728aa9cc359b,
  64'he2b989dc81aa030f,
  64'hf57a25c72be815ac
};

// SHAKE256_128B_PAD1
localparam logic [63:0] kat_SHAKE256_128B_PAD1 [4] = '{
  64'h567c48d3964b8622,
  64'hd248e574457eaae1,
  64'hc896aaf12d12c1f9,
  64'hbacbf3d203748741
};

// SHA3_256_120B_PAD2
localparam logic [63:0] kat_SHA3_256_120B_PAD2 [4] = '{
  64'hb598eaade0f1e1b6,
  64'hd029f36d194668f4,
  64'h38d404dc6aa017c6,
  64'h987afda8c1dc5425
};

// SHA3_512_56B_PAD2
localparam logic [63:0] kat_SHA3_512_56B_PAD2 [8] = '{
  64'h85a4f68e97c78377,
  64'h07980bcf3c239789,
  64'h13899d0e55ccff94,
  64'hc9444d5f5d6e22a7,
  64'hbb92aa03f36a11c1,
  64'h98b4a975ab711ae8,
  64'h1fb5f352199848da,
  64'h4f2dbd5056014b50
};

// SHAKE128_RC
localparam logic [63:0] kat_SHAKE128_RC [24] = '{
  64'h5720baeeaab9c6dd,
  64'hd3039d47d06659a2,
  64'ha4e9c5de7b6e5d10,
  64'he1c88350fb5165a3,
  64'h393e6d0bbac2f31c,
  64'h44b92eb444b7137d,
  64'h768541759d694f73,
  64'h2757c39559903e75,
  64'hb39856a562e74ee1,
  64'h97c85a64b70626ad,
  64'h511e419b6a802a9c,
  64'hff13e7ba8dbb6df9,
  64'hd6faeabe3366ba0f,
  64'he761f093f024d530,
  64'h965881d8c3737c21,
  64'hf52c8325d0839b49,
  64'h88c4d5f2c35d05c7,
  64'h95fefee75bb06e89,
  64'hb9d0aba07318b686,
  64'h66389b295ed18325,
  64'hbf681e630749d3ec,
  64'hd05a02a940d4c5ca,
  64'h8c617724038368fa,
  64'h59fd41278c3320e6
};

